"""Rebuild B16 statistics and paper tables; no model calls.
The Holm family is all 16 simple effects, defined during post-result analysis.
"""
import hashlib
import json
from math import comb
from pathlib import Path
import subprocess
import sys

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
CELLS = [('deployment', 'Gemma-4-31B'), ('deployment', 'Qwen3.8-27B'),
         ('taubench', 'Gemma-4-31B'), ('taubench', 'Qwen3.8-27B')]
COND = ['st2x2_partitioned_stop', 'st2x2_partitioned_exhaust',
        'st2x2_uniform_stop', 'st2x2_uniform_exhaust']


def exact_mcnemar(b, c):
    n = b + c
    if n == 0:
        return 1.0  # bookkeeping only; not evidence of equivalence
    return min(1.0, 2 * sum(comb(n, i) for i in range(min(b, c) + 1)) / 2**n)


def holm(pvalues):
    adjusted = [0.0] * len(pvalues)
    running = 0.0
    for rank, index in enumerate(sorted(range(len(pvalues)), key=pvalues.__getitem__)):
        running = max(running, min(1.0, (len(pvalues) - rank) * pvalues[index]))
        adjusted[index] = running
    return adjusted


def summarize(rows):
    comparisons, counts, interactions = [], [], []
    for dom, model in CELLS:
        cells = {c: rows[f'{dom}|{model}|{c}'] for c in COND}
        if any(set(r) != {str(i) for i in range(20)} for r in cells.values()):
            raise ValueError(f'Unmatched or missing seeds in {dom}/{model}')
        counts.append(dict(domain=dom, model=model, exact={
            c: sum(r['exact'] for r in cells[c].values()) for c in COND}))
        for factor, fixed_values in [('selection', ['stop', 'exhaust']),
                                     ('termination', ['partitioned', 'uniform'])]:
            for fixed in fixed_values:
                if factor == 'selection':
                    a, b = f'st2x2_partitioned_{fixed}', f'st2x2_uniform_{fixed}'
                else:
                    a, b = f'st2x2_{fixed}_exhaust', f'st2x2_{fixed}_stop'
                aa, bb = cells[a], cells[b]
                ab = sum(aa[s]['exact'] and not bb[s]['exact'] for s in aa)
                ba = sum(bb[s]['exact'] and not aa[s]['exact'] for s in aa)
                comparisons.append(dict(domain=dom, model=model, factor=factor, fixed=fixed,
                    a=a, b=b, n=20, a_only=ab, b_only=ba, difference_pp=5 * (ab - ba),
                    raw_p=exact_mcnemar(ab, ba), no_discordant_pairs=ab + ba == 0))
        p, pe, u, ue = [cells[c] for c in COND]
        diffs = [int(pe[s]['exact']) - int(p[s]['exact'])
                 - int(ue[s]['exact']) + int(u[s]['exact']) for s in p]
        interactions.append(dict(domain=dom, model=model,
            difference_in_differences_pp=5 * sum(diffs),
            inference='descriptive_only_not_a_test_of_no_interaction'))
    for c, adjusted in zip(comparisons, holm([c['raw_p'] for c in comparisons])):
        c['holm_p'] = adjusted
    return dict(family='all_16_B16_simple_effect_tests', family_size=16,
        analysis_timing='multiplicity_family_defined_after_results',
        outcome='closure_exact; parse failures retained as non-exact in denominator 20',
        pooling='no pooled cross-domain/model inferential p-values',
        counts=counts, comparisons=comparisons, interactions=interactions)


def latex_tables(result):
    lines = [r'% Generated by analysis/b16/paired_tests.py; do not edit.',
        r'\begin{table}[htbp]\centering\small',
        r'\caption{B16 common-loop factorial: exact/20, including initial parse failures. '
        r'P: candidate-partitioned; U: global uniform; S: stop; E: continue auditing.}',
        r'\label{tab:b16-counts}', r'\begin{tabular}{llrrrr}\toprule',
        r'Domain & Model & P--S & P--E & U--S & U--E \\\midrule']
    for c in result['counts']:
        dom = 'Deployment' if c['domain'] == 'deployment' else r'$\tau$-bench'
        model = 'Gemma-31B' if c['model'] == 'Gemma-4-31B' else 'Qwen3.8'
        lines.append(' & '.join([dom, model] + [str(c['exact'][k]) for k in COND]) + r' \\')
    lines += [r'\bottomrule\end{tabular}\end{table}',
        r'\begin{table}[htbp]\centering\footnotesize',
        r'\caption{B16 paired simple effects. Selection: P minus U; termination: E minus S. '
        r'Holm correction covers all 16 comparisons, including zero-discordance rows. '
        r'Dashes indicate no discordant pairs (bookkeeping $p=1$), not equivalence.}',
        r'\label{tab:b16-tests}', r'\begin{tabular}{llllrrr}\toprule',
        r'Domain & Model & Effect & Fixed & $a{:}b$ & Raw $p$ & Holm $p$ \\\midrule']
    for c in result['comparisons']:
        dom = 'Deploy.' if c['domain'] == 'deployment' else r'$\tau$-bench'
        model = 'Gemma-31B' if c['model'] == 'Gemma-4-31B' else 'Qwen3.8'
        effect = 'Selection' if c['factor'] == 'selection' else 'Termination'
        fixed = {'stop': 'S', 'exhaust': 'E', 'partitioned': 'P', 'uniform': 'U'}[c['fixed']]
        ps = ['--', '--'] if c['no_discordant_pairs'] else [f"{c[k]:.3g}" for k in ['raw_p', 'holm_p']]
        lines.append(' & '.join([dom, model, effect, fixed, f"{c['a_only']}:{c['b_only']}"] + ps) + r' \\')
    lines += [r'\bottomrule\end{tabular}\end{table}']
    return '\n'.join(lines) + '\n'


def main():
    subprocess.run([sys.executable, str(HERE / 'aggregate.py')], check=True)
    result = summarize(json.loads((ROOT / 'outputs/b16_rows.json').read_text()))
    files = sorted(p for d in ROOT.glob('results/b16_*_st2x2')
                   for p in d.glob('st2x2_*__seed*.json'))
    if len(files) != 320:
        raise ValueError(f'Expected 320 source artifacts, got {len(files)}')
    result['source_sha256'] = {str(p.relative_to(ROOT)): hashlib.sha256(p.read_bytes()).hexdigest() for p in files}
    (ROOT / 'outputs/b16_statistics.json').write_text(json.dumps(result, indent=2) + '\n')
    (ROOT / 'outputs/appendix_b16_tables.tex').write_text(latex_tables(result))
    for c in result['comparisons']:
        print(c['domain'], c['model'], c['factor'], c['fixed'],
              f"{c['a_only']}:{c['b_only']}", 'Holm', c['holm_p'])


if __name__ == '__main__':
    main()
