"""Build the manuscript fragment and residual-error counts for the 09-26 hosted cohort.

Read-only with respect to results/: consumes only comparison.json (produced by
compare.py from the 940 explicit manifest paths) and the verified local
error-asymmetry aggregate.  Writes:
  outputs/hosted_gapfill_table.tex
  analysis/openai_api_20260926/residual_direction.json
"""
from __future__ import annotations

import hashlib
import json
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
HERE = ROOT / "analysis/openai_api_20260926"
COMPARISON = HERE / "comparison.json"
LOCAL = ROOT / "analysis/error_asymmetry_20260926/results.json"
TABLE = (ROOT / "outputs/hosted_gapfill_table.tex" if (ROOT / "paper/iclr2027").is_dir()
         else HERE / "hosted_gapfill_table.tex")  # anonymous release has no paper/
OUT = HERE / "residual_direction.json"

MODELS = [("gpt-5.6-terra", "GPT-5.6 terra"), ("gpt-5.6-luna", "GPT-5.6 luna"),
          ("gpt-5.4-nano", "GPT-5.4 nano"), ("gpt-5.4-mini", "GPT-5.4 mini")]
DOMAINS = [("deployment", "Deployment"), ("taubench", "Retail"),
           ("calendar", "Calendar"), ("shopping_price", "Shopping")]
METHODS = ["direct", "self_refine", "fixed_pool", "active_cegis", "active_cegis_no_balance"]
LABEL = {"fixed_pool": "Fixed-pool", "active_cegis": "Active",
         "active_cegis_no_balance": "No-Balance", "self_refine": "Self-Refine", "direct": "Direct"}


def sha(p: Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()


def direction(run: dict) -> str | None:
    """Classify a valid inexact run; None for parse failures and exact runs."""
    m = run.get("metrics")
    if run.get("parse_failure") or run.get("exact") or not m:
        return None
    fa, fr = m.get("false_accepts", 0), m.get("false_rejects", 0)
    return "fa_gt_fr" if fa > fr else "fa_lt_fr" if fr > fa else "fa_eq_fr"


def main() -> None:
    comp = json.loads(COMPARISON.read_text())
    cells = comp["cells"] if isinstance(comp["cells"], list) else list(comp["cells"].values())
    index = {(c["model"], c["domain"], c["method"]): c for c in cells}
    assert len(index) == 47 and all(c["n"] == 20 for c in cells)

    rows = []
    for mk, mname in MODELS:
        for i, (dk, dname) in enumerate(DOMAINS):
            entries = []
            for meth in METHODS:
                c = index.get((mk, dk, meth))
                if c is None:
                    entries.append("--")
                    continue
                txt = f"{c['exact']} ({c['cfr_mean']:.1f})"
                entries.append(f"\\textbf{{{txt}}}" if meth == "active_cegis" else txt)
            rows.append(f"{mname if i == 0 else ''} & {dname} & " + " & ".join(entries) + r" \\")
        rows.append(r"\addlinespace[2pt]")
    rows.pop()

    TABLE.write_text("\n".join([
        "% Generated by analysis/openai_api_20260926/appendix_gapfill.py; do not edit.",
        r"\begin{tabular}{llrrrrr}",
        r"\toprule",
        r"Model & Domain & Direct & Self-Refine & Fixed-pool & \textbf{Active} & No-Balance \\",
        r"\midrule",
        *rows,
        r"\bottomrule",
        r"\end{tabular}",
        "",
    ]))

    hosted = {}
    for meth in ("fixed_pool", "active_cegis_no_balance", "active_cegis"):
        cnt = Counter(d for c in cells if c["method"] == meth
                      for d in map(direction, c["runs"]) if d)
        hosted[LABEL[meth]] = dict(cnt)
    local = json.loads(LOCAL.read_text())["claims"]
    local_counts = {
        "Fixed-pool": local["main"]["Fixed-pool"]["counts"],
        "Active": local["main"]["Active"]["counts"],
        "No-Balance": local["ablation"]["No-Balance"]["counts"],
    }
    OUT.write_text(json.dumps({
        "definition": "valid (parsed) inexact runs; fa_gt_fr / fa_lt_fr / fa_eq_fr by stored FA and FR",
        "inputs": {str(COMPARISON.relative_to(ROOT)): sha(COMPARISON), str(LOCAL.relative_to(ROOT)): sha(LOCAL)},
        "hosted_20260926": hosted,
        "local_verified": {k: {x: v[x] for x in ("fa_gt_fr", "fa_lt_fr", "fa_eq_fr")} for k, v in local_counts.items()},
    }, indent=1) + "\n")
    print(json.dumps(json.loads(OUT.read_text())["hosted_20260926"]))
    print(json.dumps(json.loads(OUT.read_text())["local_verified"]))


if __name__ == "__main__":
    main()
